"""empty message

Revision ID: 243c2d8568bd
Revises: 
Create Date: 2023-07-26 11:24:03.991857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243c2d8568bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('ingredients', sa.String(length=200), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=200), nullable=True),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    op.drop_table('meals')
    # ### end Alembic commands ###
